easy_admin:
    site_name: 'eina BLOG'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
        
    list:
        max_results: 100
        
    entities:
        Post:
            class: AppBundle\Entity\Post
            list:
                title: list.title
                fields:
                    - 'fechaEntrega'
                    - 'titulo'
                    - 'cadencia'
                    - 'acabado'
                    - 'autor'
                actions:
                    - { name: 'show', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }

        User:
            label: 'Usuarios'
            class: AppBundle\Entity\User
            list:
                title: user.title